# Generated by Django 5.2.6 on 2025-09-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام کامل مخاطب", max_length=100, verbose_name="نام"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="شماره موبایل یا تلفن ثابت",
                        max_length=20,
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="ایمیل اختیاری",
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="زمان ایجاد مخاطب",
                        verbose_name="تاریخ ایجاد",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر تیک خورده باشد، مخاطب فعال است",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "not_activated",
                    models.BooleanField(
                        default=False,
                        help_text="اگر تیک خورده باشد، مخاطب هنوز فعال نشده است",
                        verbose_name="غیرفعال شده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخاطب",
                "verbose_name_plural": "مخاطبین",
                "ordering": ["name"],
            },
        ),
    ]
