# Generated by Django 5.2.6 on 2025-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="شماره تماس"),
        ),
    ]
